### ISSUE TITLE
cant run datatable*.py examples

### ISSUE THREAD

**Issue by alberto-bortoni** [tonycpsu/panwid#24]
Perhaps something very simple, but I get this error as I run any of the datatable examples:
Thank you!!

Traceback (most recent call last):
  File "/media/sf_vboxshare/urwid-examples/panwid-main/examples/datatable_simple.py", line 62, in <module>
    main()
  File "/media/sf_vboxshare/urwid-examples/panwid-main/examples/datatable_simple.py", line 53, in main
    loop = urwid.MainLoop(
  File "/home/money/.local/lib/python3.10/site-packages/urwid/event_loop/main_loop.py", line 127, in __init__
    screen.register_palette(palette)
  File "/home/money/.local/lib/python3.10/site-packages/urwid/display_common.py", line 1041, in register_palette
    self.register_palette_entry(*item)
  File "/home/money/.local/lib/python3.10/site-packages/urwid/display_common.py", line 1122, in register_palette_entry
    mono = AttrSpec(mono, DEFAULT, 1)
  File "/home/money/.local/lib/python3.10/site-packages/urwid/display_common.py", line 597, in __init__
    raise AttrSpecError(
urwid.display_common.AttrSpecError: foreground/background ('white'/'default') require more colors than have been specified (1).

**Comment by doctorcolossus** [comment]
Same here.

Actually I get that error for `datatable.py`, `datatable_simple.py`, `dropdown.py`, and  `progressbar.py`.

For `datatable_simple_query.py`, I instead get:
`AttributeError: module 'pydantic' has no attribute 'main'`
The database examples give this error too if the palette error is fixed (I did this by removing the `palette = palette` argument to `urwid.MainLoop`).

`sparkwidgets.py`  gives:
`AttributeError: module 'collections' has no attribute 'Iterable'`

`dialog.py` runs fine.

Using Python 3.11.6.
